<?php

/**
 * @file: OrderResource.php
 * @description: API Resource for the Eloquent Order model consumed by the
 *               FleetOps Operations frontend (orders/view.js).
 *
 *               KEY REQUIREMENT — tracking_url
 *               ─────────────────────────────
 *               The frontend reads order.tracking_url to render the clickable
 *               customer portal link. It must follow this exact format:
 *                 http://127.0.0.1:3002/track?token={uuid}
 *
 *               The UUID token lives in LiveTrackingLink on the order row.
 *               It is a UUID generated by Order::booted() at creation time.
 *               It is NEVER the integer OrderID.
 *
 * @module: OrderManagement
 */

namespace App\Modules\OrderManagement\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Str;

class OrderResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        // Resolve the UUID tracking token from LiveTrackingLink.
        // If the column still holds the old "http://fleetops.com/..." value
        // (legacy orders written before the boot hook was added), we strip it
        // and fall back to a freshly generated token so the URL is always valid.
        $token = $this->resolveToken();

        return [
            // ── Identity ──────────────────────────────────────────────────
            'id'              => $this->OrderID,
            'order_id'        => $this->OrderID,
            'status'          => $this->Status ?? 'Pending',

            // tracking_token is the UUID hash string, NEVER the integer ID.
            'tracking_token'  => $token,

            // Exact format required by orders/view.js:
            //   http://127.0.0.1:3002/track?token={uuid}
            'tracking_url'    => config('app.customer_portal_url', 'http://127.0.0.1:3002')
                                 . '/track?token=' . $token,

            // ── Customer ──────────────────────────────────────────────────
            'customer_name'   => optional($this->customer?->user)->name ?? 'N/A',
            'customer_phone'  => optional($this->customer?->user)->phone_no ?? 'N/A',
            'customer_email'  => optional($this->customer?->user)->email ?? 'N/A',

            // ── Delivery ──────────────────────────────────────────────────
            'delivery_address' => $this->Area ?? 'N/A',
            'latitude'         => $this->Latitude  ? (float) $this->Latitude  : null,
            'longitude'        => $this->Longitude ? (float) $this->Longitude : null,
            'eta'              => $this->ETA,
            'promised_window'  => $this->PromisedWindow,
            'delivered_at'     => $this->DeliveredAt,

            // ── Order Details ─────────────────────────────────────────────
            'type'             => $this->Type ?? 'Normal',
            'priority'         => $this->Priority ?? 40,
            'price'            => $this->Price ? (float) $this->Price : null,
            'payment_method'   => $this->Payment_method ?? 'N/A',
            'weight'           => $this->Weight ? (int) $this->Weight : null,
            'volume'           => $this->Volume ? (int) $this->Volume : null,
            'perishable'       => (bool) ($this->Perishable ?? false),
            'delivery_preference' => $this->Delivery_preference ?? null,

            // ── Driver / Vehicle ──────────────────────────────────────────
            'driver_id'        => $this->{'DriverID(FK)'} ?? null,
            'driver_name'      => optional($this->driver?->user)->name ?? null,
            'vehicle_id'       => $this->{'vehicle_id(FK)'} ?? null,

            // ── Timestamps ────────────────────────────────────────────────
            'created_at'       => $this->Created_at,
            'updated_at'       => $this->UpdatedAt,
        ];
    }

    /**
     * Resolve the UUID token from LiveTrackingLink.
     *
     * Handles two legacy cases:
     *   - Old hardcoded URL: "http://fleetops.com/track/1001"  → generates fresh UUID
     *   - Null / empty                                          → generates fresh UUID
     *   - Already a valid UUID string                           → returned as-is
     *
     * Note: if a fresh UUID is generated here it is NOT persisted — it only
     * affects this response. A backfill command should be run to fix the DB rows.
     */
    private function resolveToken(): string
    {
        $raw = $this->LiveTrackingLink ?? '';

        // Looks like the old hardcoded URL pattern or is empty → generate fallback
        if (
            empty($raw)
            || str_starts_with($raw, 'http://')
            || str_starts_with($raw, 'https://')
        ) {
            return (string) Str::uuid();
        }

        return $raw;
    }
}
